/*
 * generated by Xtext
 */
package org.xtext.jlog.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JlogDslUiModule extends org.xtext.jlog.ui.AbstractJlogDslUiModule {
	public JlogDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
