/*
* generated by Xtext
*/
package org.xtext.jlog;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JlogDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.jlog.ui.internal.JlogDslActivator.getInstance().getInjector("org.xtext.jlog.JlogDsl");
	}
	
}
