/*
 * generated by Xtext
 */
package org.xtext.jlog.ui.contentassist

import org.xtext.jlog.ui.contentassist.AbstractJlogDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JlogDslProposalProvider extends AbstractJlogDslProposalProvider {
}
