/**
 * generated by Xtext
 */
package org.xtext.jlog.validation;

import org.xtext.jlog.validation.AbstractJlogDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class JlogDslValidator extends AbstractJlogDslValidator {
}
