/*
 * generated by Xtext
 */
package org.xtext.jlog.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.jlog.ui.internal.JlogDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JlogDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JlogDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JlogDslActivator.getInstance().getInjector(JlogDslActivator.ORG_XTEXT_JLOG_JLOGDSL);
	}
	
}
