/*
 * generated by Xtext
 */
package org.xtext.jlog;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JlogDslRuntimeModule extends org.xtext.jlog.AbstractJlogDslRuntimeModule {

}
