/*
* generated by Xtext
*/
package org.xtext.jlog;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JlogDslStandaloneSetup extends JlogDslStandaloneSetupGenerated{

	public static void doSetup() {
		new JlogDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

