/*
* generated by Xtext
*/
package org.xtext.jlog.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.jlog.services.JlogDslGrammarAccess;

public class JlogDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JlogDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.jlog.parser.antlr.internal.InternalJlogDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.jlog.parser.antlr.internal.InternalJlogDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Jlog";
	}
	
	public JlogDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JlogDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
