/**
 *
 * $Id$
 */
package quality_requirements_metamodel.validation;


/**
 * A sample validator interface for {@link quality_requirements_metamodel.Stimulus}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StimulusValidator {
	boolean validate();

	boolean validateName(String value);
}
